default: &default
  adapter: postgresql
  encoding: unicode
  username: pzazos_website
  password: 56693728
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: pzazos_website_development

test:
  <<: *default
  database: pzazos_website_test

production:
  <<: *default
  database: pzazos_website_production
  username: pzazos_website
  password: <%= ENV['PZAZOS_WEBSITE_DATABASE_PASSWORD'] %>
